### ISSUE TITLE
academic access 

### ISSUE THREAD

**Issue by bibo702** [pwichmann/supply_chain_mining#1]
In my Master Thesis will be mainely based on your work and would like to to replicate itto extract relation  between supplier and buyer from the news data set and test it in others.
Could you please procure the necesary scripts to replicate the work of the paper in order to understand the steps and get a better insight over the pipline? 
Thank you 
Best regards

**Comment by pwichmann** [comment]
Dear @bibo702,
I am incredibly sorry for not having responded. I must have been in the midst of a project. 2020 has been a nightmarish year for many - me included. There was no intent in not responding to your request. 

Did you end up writing about the topic in your thesis?
If so, feel free to reach out here. I'd be very interested.

Cheers
Pascal
