### ISSUE TITLE
academic access

### ISSUE THREAD

**Issue by xieexiaotuzi** [pwichmann/supply_chain_mining#2]
Hi Dr. Pascal Wichmann,
    I am Jason, a Ph.D. student from Queens University.
    Thanks for sharing the paper. I think that it is the first step to try NLP and DL in the supply chain map.
    I would like to try some academic research based on your excellent work. Could you please send me the data (before pre-processing and after pre-processing) and some necessary codes to reproduce the results? I guarantee that I will not use it for any commercial purpose. My academic e-mail is 20jz43@queensu.ca .
     Thanks a lot.

Best,
    Jason.

**Comment by pwichmann** [comment]
Dear Jason,

Sorry for the slight delay. I will contact you from my gmail email account.

Cheers
Pascal
