### ISSUE TITLE
academic access

### ISSUE THREAD

**Issue by erip** [pwichmann/supply_chain_mining#3]
Hi Pascal, I'm a PhD student at the University of Maryland where I focus on applied NLP. One such application area that my colleagues and I are interested in exploring is supply chain mapping and downstream analytics. I was hoping you might be willing to share data for replicability and benchmarking some of our future approaches. You can contact me at erip [at] umd [dot] edu.

**Comment by pwichmann** [comment]
Dear @erip,

Many thanks for your request.
I will contact you via my gmail account.

Cheers
Pascal
