### ISSUE TITLE
Academic access

### ISSUE THREAD

**Issue by liujy-2000** [pwichmann/supply_chain_mining#6]
Hi Dr. Wichmann,
I am a senior student of Beihang University majoring in Computer Science and Technology. After reading your thesis, I got a lot of inspiration. Would it possible for me to refer to your data and code in my undergraduate thesis? Also, it would be a great help if I could obtain the data and some necessary codes from you to reproduce the results. 

You may contact me at 18373157@buaa.edu.cn.
I am looking forward to your reply.

Many Thanks!

Best,
Jiayu Liu

**Comment by pwichmann** [comment]
I am sorry for the late reply. I am in the process of setting up a private repository with the data.
Please let me know if this is still relevant.

**Comment by liujy-2000** [comment]
So sorry for the late reply. It is no so convenient to sign up github in China. The relevent program have done so the code and data is not needed anymore. Thank you for your kindhearted reply! Best wishs to you!
